name: Dispatch

on:
  # Manual runs.
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Target Environment"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - stage
          - performance
          - cps-preview
          - training
          - uat
          - breakfix
          - trn2
jobs:
  trigger:
    name: E2E Tests (multiple)
    uses: ./.github/workflows/tocall.yml
    with:
      target_environment: ${{ github.event.inputs.target_environment }}
      random_input: ${{ github.event.inputs.target_environment == 'test' && 'Target is test' || 'Target is NOT test'  }}
