on: 
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs: 
  jira:
    name: Jira tickets
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with: { node-version: "16.x" }
      - name: Execute Jira tickets creation.
        run: node -v
