name: "Workflow to call"
on:
  # Note: Inputs must be kept in sync between workflow_call and workflow_run.
  workflow_call:
    inputs:
      target_environment:
        description: "Target Environment"
        default: "test"
        type: string
jobs:
  ping:
    name: Health Check ** ${{ inputs.target_environment }} **
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Ping Example site"
        run: curl "https://www.example.com"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: { node-version: "18.x" }
      - name: Create a folder
        run: mkdir e2e
      - name: "Install Node Modules"
        uses: bahmutov/npm-install@v1
        with:
          working-directory: e2e  

