#
# This workflow actually runs E2E tests: Cypress and Jest.
#
# It is a "reusable" workflow, meaning it can only be triggered as part of another workflow.
# It runs tests in parallel, and tests are split into four categories:
#   * Stable - tests that must pass before release.
#   * Unstable - tests that are advisory (for upcoming features) and should not block release.
#   * Ignored - tests that are not run at all in CI.
#   * Morning - tests that run to check features are working correctly.
# This name shouldn't matter, as it isn't displayed. We add "ZZ" to make it float to the bottom
# of the workflows list in case it somehow gets triggered directly.
name: "ZZ: E2E Tests"
on:
  # Note: Inputs must be kept in sync between workflow_call and workflow_run.
  workflow_call:
    inputs:
      target_environment:
        description: "Target Environment"
        default: "test"
        type: string
      random_input: 
        description: "To test"
        type: string
jobs:
  ping:
    name: Health Check ** ${{ inputs.target_environment }} **
    runs-on: ubuntu-latest
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
    steps:
      - name: "Install curl"
        run: apt-get -y update; apt-get -y install curl
      - uses: actions/checkout@v3
      - name: "Ping Example site"
        run: curl "https://www.example.com"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: { node-version: "18.x" }
      - name: "Create a folder"
        id: create
        run: mkdir e2e
      - name: "List folders"
        id: ls
        run: ls
        continue-on-error: true
      - name: "Confirm e2e folder"
        id: confirm
        if: steps.ls.outcome == 'cancelled'
        run: cd e2e && ls
      - name: "Check confirm"
        if: steps.ls.outcome == 'skipped'
        run: cd e2e && ls
        

