name: "Workflow to call"
on:
  # Note: Inputs must be kept in sync between workflow_call and workflow_run.
  workflow_call:
    inputs:
      target_environment:
        description: "Target Environment"
        default: "test"
        type: string
jobs:
  ping:
    name: Health Check ** ${{ inputs.target_environment }} **
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Ping Example site"
        run: curl "https://www.example.com"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: { node-version: "18.x" }
      - name: "Create a folder"
        id: create
        run: mkdir e2e
      - name: "List folders"
        id: ls
        run: ls
        continue-on-error: true
      - name: "Confirm e2e folder"
        if: steps.ls.status == 'success'
        run: cd e2e && ls
        

